# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
            ],
        ),
    ]
